
version: "3.9"

services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app/'
      - node_modules:/app/node_modules
    networks:
      - cintelinl-client

volumes:
  node_modules:

networks:
  cintelinl-client:

